### ISSUE TITLE
[MediaContent] Wrong Implement of Dispose pattern 

### ISSUE THREAD

**Issue by myroot** [Samsung/TizenFX#70] opened 2018-01-23 06:58 UTC
https://github.com/Samsung/TizenFX/blob/3566375f1189cdcd03f869fae78eabd77bbe3a3b/src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/ObjectKeeper.cs#L52-L63

_handle should be always freed. 

https://msdn.microsoft.com/ko-kr/library/system.runtime.interopservices.gchandle(v=vs.110).aspx
```When the handle goes out of scope you must explicitly release it by calling the M:System.Runtime.InteropServices.GCHandle.Free method; otherwise, memory leaks may occur. When you free a pinned handle, the associated object will be unpinned and will become eligible for garbage collection, if there are no other references to it.```

**Comment by coderhyme** [comment] 2018-01-24 05:09
You mean the problem is when the disposing value is false. Right?

**Comment by myroot** [comment] 2018-01-24 05:11
Yes, the disposing value was false when disposed by finalizer and in this case _handle was not released

**Comment by coderhyme** [comment] 2018-01-25 10:46
Has been fixed by (https://github.com/Samsung/TizenFX/pull/81).

**Closed by coderhyme** 2018-01-25 10:46 UTC
